
// General purpose contants
export const PROCESSING_DATA = 'PROCESSING_DATA';
export const PROCESS_SUCCESS = 'PROCESS_SUCCESS';
export const PROCESS_FAILURE = 'PROCESS_FAILURE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

// Auth constants
export const AUTH_REQ_VERIFY_CODE = 'AUTH_REQ_VERIFY_CODE';
export const AUTH_REQ_REGISTER = 'AUTH_REQ_REGISTER';
export const AUTH_REQ_RECOVER_CODE = 'AUTH_REQ_RECOVER_CODE';
export const AUTH_REQ_RECOVER = 'AUTH_REQ_RECOVER';
export const AUTH_REQ_LOGIN = 'AUTH_REQ_LOGIN';
export const AUTH_REQ_QLOGIN = 'AUTH_REQ_QLOGIN';
export const AUTH_REQ_LOGOUT = 'AUTH_REQ_LOGOUT';
export const AUTH_REQ_REFRESH = 'AUTH_REQ_REFRESH';
export const AUTH_REQ_CURRENT_USER = 'AUTH_REQ_CURRENT_USER';

export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_REFRESH_SUCCESS = 'AUTH_REFRESH_SUCCESS';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_GETUSER_SUCCESS = 'AUTH_GETUSER_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


// User constants
export const USER_REQ_RECENT_NETWORK = 'USER_REQ_RECENT_NETWORK';
export const USER_REQ_CURRENT_NETWORK = 'USER_REQ_CURRENT_NETWORK';
export const USER_REQ_ADD_NETWORK = 'USER_REQ_ADD_NETWORK';
export const USER_REQ_ASSIGNABLE_COUPON = 'USER_REQ_ASSIGNABLE_COUPON';
export const USER_REQ_ASSIGN_COUPON = 'USER_REQ_ASSIGNE_COUPON';

export const USER_RECENT_SUCCESS = 'USER_RECENT_SUCCESS';
export const USER_CURRENT_SUCCESS = 'USER_CURRENT_SUCCESS';
export const USER_ASSIGNABLE_SUCCESS = 'USER_ASSIGNABLE_SUCCESS';
export const USER_SET_LOCATION = 'USER_SET_LOCATION';
export const USER_SET_CITY = 'USER_SET_CITY';


// Food constants
export const FOOD_REQ_SALEABLE = 'FOOD_REQ_SALEABLE';
export const FOOD_REQ_SALE_TIME = 'FOOD_REQ_SALE_TIME';
export const FOOD_REQ_POPULAR = 'FOOD_REQ_POPULAR';
export const FOOD_REQ_INTEREST = 'FOOD_REQ_INTEREST';
export const FOOD_REQ_DETAIL = 'FOOD_REQ_DETAIL';
export const FOOD_REQ_COMMENT = 'FOOD_REQ_COMMENT';
export const FOOD_REQ_SPECIALS = 'FOOD_REQ_SPECIALS';

export const FOOD_SALEABLE_SUCCESS = 'FOOD_SALEABLE_SUCCESS';
export const FOOD_SALE_TIME_SUCCESS = 'FOOD_SALE_TIME_SUCCESS';
export const FOOD_POPULAR_SUCCESS = 'FOOD_POPULAR_SUCCESS';
export const FOOD_INTEREST_SUCCESS = 'FOOD_INTEREST_SUCCESS';
export const FOOD_DETAIL_SUCCESS = 'FOOD_DETAIL_SUCCESS';
export const FOOD_COMMENT_SUCCESS = 'FOOD_COMMENT_SUCCESS';
export const FOOD_SPECIALS_SUCCESS = 'FOOD_SPECIALS_SUCCESS';


// City constants
export const CITY_REQ_ACTIVE = 'CITY_REQ_ACTIVE';
export const CITY_REQ_NEARBY = 'CITY_REQ_NEARBY';

export const CITY_ACTIVE_SUCCESS = 'CITY_ACTIVE_SUCCESS';
export const CITY_NEARBY_SUCCESS = 'CITY_NEARBY_SUCCESS';


// Order constants
export const ORDER_REQ_AVAILABLE_COUPON = 'ORDER_REQ_AVAILABLE_COUPON';
export const ORDER_REQ_AVAILABLE_DISCOUNT = 'ORDER_REQ_AVAILABLE_DISCOUNT';
export const ORDER_REQ_CREATE = 'ORDER_REQ_CREATE';
export const ORDER_REQ_DINING_CODES = 'ORDER_REQ_DINING_CODES';
export const ORDER_REQ_DINING_DETAIL = 'ORDER_REQ_DINING_DETAIL';
export const ORDER_REQ_CLEAR_DETAIL = 'ORDER_REQ_CLEAR_DETAIL';
export const ORDER_INCREASE_FOOD = 'ORDER_INCREASE_FOOD';
export const ORDER_DECREASE_FOOD = 'ORDER_DECREASE_FOOD';
export const ORDER_SET_ORDER_TIME = 'ORDER_SET_ORDER_TIME';
export const ORDER_RESET_SHOPPING = 'ORDER_RESET_SHOPPING';
export const ORDER_SET_COUPON = 'ORDER_SET_COUPON';

export const ORDER_AVAILABLE_COUPON_SUCCESS = 'ORDER_AVAILABLE_COUPON_SUCCESS';
export const ORDER_AVAILABLE_FULLOFF_SUCCESS = 'ORDER_AVAILABLE_FULLOFF_SUCCESS';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_DINING_SUCCESS = 'ORDER_DINING_SUCCESS';
export const ORDER_DINING_DETAIL_SUCESS = 'ORDER_DINING_DETAIL_SUCESS';


// Config constants
export const CONFIG_REQ_PAYMENT_GATEWAY = 'CONFIG_REQ_PAYMENT_GATEWAY';
export const CONFIG_PAYMENT_GATEWAY_SUCCESS = 'CONFIG_PAYMENT_GATEWAY_SUCCESS';

// Deposit constants
export const DEPOSIT_REQ_ACTIVE_LIST = 'DEPOSIT_REQ_ACTIVE_LIST';
export const DEPOSIT_ACTIVE_LIST_SUCCESS = 'DEPOSIT_ACTIVE_LIST_SUCCESS';

// Pay constants
export const PAY_REQ_APP_PAY = 'PAY_REQ_APP_PAY';
export const PAY_REQ_SCAN_PAY = 'PAY_REQ_SCAN_PAY';
export const PAY_REQ_SUCCESS = 'PAY_REQ_SUCCESS';

// Account constants
export const ACCOUNT_REQ_BALANCE_HISTORY = 'ACCOUNT_REQ_BALANCE_HISTORY';
export const ACCOUNT_REQ_POINT_HISTORY = 'ACCOUNT_REQ_POINT_HISTORY';
export const ACCOUNT_REQ_PENDING_ORDER = 'ACCOUNT_REQ_PENDING_ORDER';
export const ACCOUNT_REQ_PAID_ORDER = 'ACCOUNT_REQ_PAID_ORDER';
export const ACCOUNT_REQ_COMPLETE_ORDER = 'ACCOUNT_REQ_COMPLETE_ORDER';
export const ACCOUNT_REQ_WAITING_COMMENT = 'ACCOUNT_REQ_WAITING_COMMENT';
export const ACCOUNT_REQ_ALREADY_COMMENT = 'ACCOUNT_REQ_ALREADY_COMMENT';
export const ACCOUNT_REQ_COUPONS = 'ACCOUNT_REQ_COUPONS';
export const ACCOUNT_REQ_UPLOAD_AVATAR = 'ACCOUNT_REQ_UPLOAD_AVATAR';
export const ACCOUNT_REQ_UPDATE_PROFILE = 'ACCOUNT_REQ_UPDATE_PROFILE';
export const ACCOUNT_REQ_CHANGE_PASSWORD = 'ACCOUNT_REQ_CHANGE_PASSWORD';
export const ACCOUNT_REQ_UPDATE_PUSHER = 'ACCOUNT_REQ_UPDATE_PUSHER';


export const ACCOUNT_BALANCE_HISTORY_SUCCESS = 'ACCOUNT_BALANCE_HISTORY_SUCCESS';
export const ACCOUNT_POINT_HISTORY_SUCCESS = 'ACCOUNT_POINT_HISTORY_SUCCESS';
export const ACCOUNT_PENDING_ORDER_SUCCESS = 'ACCOUNT_PENDING_ORDER_SUCCESS';
export const ACCOUNT_PAID_ORDER_SUCCESS = 'ACCOUNT_PAID_ORDER_SUCCESS';
export const ACCOUNT_COMPLETE_ORDER_SUCCESS = 'ACCOUNT_COMPLETE_ORDER_SUCCESS';
export const ACCOUNT_WAITING_COMMENT_SUCCESS = 'ACCOUNT_WAITING_COMMENT_SUCCESS';
export const ACCOUNT_ALREADY_COMMENT_SUCCESS = 'ACCOUNT_ALREADY_COMMENT_SUCCESS';
export const ACCOUNT_COUPONS_SUCCESS = 'ACCOUNT_COUPONS_SUCCESS';
export const ACCOUNT_UPLOAD_AVATAR_SUCCESS = 'ACCOUNT_UPLOAD_AVATAR_SUCCESS';
export const ACCOUNT_UPDATE_PROFILE_SUCCESS = 'ACCOUNT_UPDATE_PROFILE_SUCCESS';
export const ACCOUNT_CHANGE_PASSWORD_SUCCESS = 'ACCOUNT_CHANGE_PASSWORD_SUCCESS';
export const ACCOUNT_UPDATE_PUSHER_SUCCESS = 'ACCOUNT_UPDATE_PUSHER_SUCCESS';

export const ACCOUNT_BALANCE_HISTORY_MORE_SUCCESS = 'ACCOUNT_BALANCE_HISTORY_MORE_SUCCESS';
export const ACCOUNT_POINT_HISTORY_MORE_SUCCESS = 'ACCOUNT_POINT_HISTORY_MORE_SUCCESS';
export const ACCOUNT_PENDING_ORDER_MORE_SUCCESS = 'ACCOUNT_PENDING_ORDER_MORE_SUCCESS';
export const ACCOUNT_PAID_ORDER_MORE_SUCCESS = 'ACCOUNT_PAID_ORDER_MORE_SUCCESS';
export const ACCOUNT_COMPLETE_ORDER_MORE_SUCCESS = 'ACCOUNT_COMPLETE_ORDER_MORE_SUCCESS';
export const ACCOUNT_WAITING_COMMENT_MORE_SUCCESS = 'ACCOUNT_WAITING_COMMENT_MORE_SUCCESS';
export const ACCOUNT_ALREADY_COMMENT_MORE_SUCCESS = 'ACCOUNT_ALREADY_COMMENT_MORE_SUCCESS';
export const ACCOUNT_COUPONS_MORE_SUCCESS = 'ACCOUNT_COUPONS_MORE_SUCCESS';

export const DISCOVER_REQ_ARTICLES = 'DISCOVER_REQ_ARTICLES';
export const DISCOVER_REQ_COMMENTS = 'DISCOVER_REQ_COMMENTS';
export const DISCOVER_ARTICLES_SUCCESS = 'DISCOVER_ARTICLES_SUCCESS';
export const DISCOVER_COMMENTS_SUCCESS = 'DISCOVER_COMMENTS_SUCCESS';